[package]
name = "bycat-geenie"
version = "0.1.0"
edition = "2024"

[features]
default = ["process"]
fs = ["async-fs", "futures"]
process = ["async-process"]

[dependencies]
bycat = { path = "../bycat" }
bycat-package = { path = "../bycat-package" }
bycat-source = { path = "../bycat-source" }

relative-path = "2"
thiserror = "2"

spurgt = { git = "ssh://git@github.com/fairy-render/spurgt.git" }
spurgt-cliclack = { git = "ssh://git@github.com/fairy-render/spurgt.git", optional = true }

async-process = { version = "2", optional = true }
async-fs = { version = "2", optional = true }
futures = { version = "0.3", optional = true }

[dev-dependencies]
ctrlc = { version = "3" }
futures = { version = "0.3", features = ["executor"] }


[[example]]
name = "geenie"
path = "examples/geenie.rs"
# required-features = ["fs", "process"]
